spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/digital_banking}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Soulsql@01}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:300000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      pool-name: ${HIKARI_POOL_NAME:AuthServiceHikariCP}

  jpa:
    hibernate:
      hbm2ddl:
        auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        use_sql_comments: true
        id:
          new_generator_mappings: true


  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    table: flyway_schema_history
    out-of-order: false
    placeholder-replacement: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
